version: '2.1'

services:
  shrink-link:
    tty: true
    stdin_open: true
    depends_on:
      - 'mongo'
    image: samrose3/shrink-link
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - BASE_URL=http://0.0.0.0:3000
      - MONGO_URL=mongodb://mongo:27017/shrink-link
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo:
